name: Build and Deploy
run-name: TODO
on:
  push:
    branches:
      - main
jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Packages
        run: npm install
      - name: Run CMS Generators
        run: |
          npm run generate-content
          npm run generate-icon-sprite
      - name: Package Site
        run: npm run build
      - name: Deploy site
        run: |
          npm run deploy
          npm run invalidate
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}